name = "drenopavfloors"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# OpenNext Assets binding
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Custom domain routes
[[routes]]
pattern = "drenopavfloors.ng/*"
zone_name = "drenopavfloors.ng"

[[routes]]
pattern = "www.drenopavfloors.ng/*"
zone_name = "drenopavfloors.ng"
